#!/usr/bin/env ruby
require File.expand_path(File.join(File.dirname(__FILE__), '..', 'config/environment'))

Dir.chdir(Rails.root)

loop do
  PdfGeneration.find_and_generate
end


# #!/bin/bash
# cd $1
# TZ=:/etc/localtime bundle exec rake pdf:generate
