#!/usr/bin/env ruby
require 'rubygems'
require 'daemons'

script = File.join(File.dirname(__FILE__), 'rocky_pdf_worker')
dir = File.expand_path(File.join(File.dirname(__FILE__), '..'))

Daemons.run(script, :ARGV => ARGV + ['--', dir],
            :mode => :exec,
            :dir_mode => :normal,
            :dir => 'tmp/pids',
            :log_output => false,
            :multiple => true)


