#!/usr/bin/env ruby
require File.expand_path(File.join(File.dirname(__FILE__), '..', 'config/environment'))

Dir.chdir(Rails.root)

loop do
  PriorityPdfGeneration.find_and_generate
  PdfGeneration.find_and_generate
end